
package com.qlc.test.byjdk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyServiceServer", targetNamespace = "http://byjdk.test.qlc.com/", wsdlLocation = "http://localhost:8080/extService?wsdl")
public class MyServiceServer
    extends Service
{

    private final static URL MYSERVICESERVER_WSDL_LOCATION;
    private final static WebServiceException MYSERVICESERVER_EXCEPTION;
    private final static QName MYSERVICESERVER_QNAME = new QName("http://byjdk.test.qlc.com/", "MyServiceServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/extService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSERVICESERVER_WSDL_LOCATION = url;
        MYSERVICESERVER_EXCEPTION = e;
    }

    public MyServiceServer() {
        super(__getWsdlLocation(), MYSERVICESERVER_QNAME);
    }

    public MyServiceServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSERVICESERVER_QNAME, features);
    }

    public MyServiceServer(URL wsdlLocation) {
        super(wsdlLocation, MYSERVICESERVER_QNAME);
    }

    public MyServiceServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSERVICESERVER_QNAME, features);
    }

    public MyServiceServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServiceServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceServerPort")
    public MyService getMyServiceServerPort() {
        return super.getPort(new QName("http://byjdk.test.qlc.com/", "MyServiceServerPort"), MyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceServerPort")
    public MyService getMyServiceServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://byjdk.test.qlc.com/", "MyServiceServerPort"), MyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSERVICESERVER_EXCEPTION!= null) {
            throw MYSERVICESERVER_EXCEPTION;
        }
        return MYSERVICESERVER_WSDL_LOCATION;
    }

}
